"""empty message

Revision ID: 59f9a864062d
Revises: 8597d3fe33e1
Create Date: 2026-02-16 18:25:39.889193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f9a864062d'
down_revision: Union[str, Sequence[str], None] = '8597d3fe33e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('prepaid_dinners_quantity',
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('prepaid_dinners_quantity',
               nullable=True)

    # ### end Alembic commands ###
